### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by estimadarocha** [Huevos/SatScanLcn#2]
Thanks for your work.

Are you aware of any troubles on openatv 7.1? after the installation of plugin the plugin doesn't show up under reception.

root@gbue4k:~# opkg install enigma2-plugin-systemplugins-satscanlcn
Installing enigma2-plugin-systemplugins-satscanlcn (1.0+git53+8520b7c) on root.
Downloading http://feeds2.mynonpublic.com/7.1/gb7252/cortexa15hf-neon-vfpv4/enigma2-plugin-systemplugins-satscanlcn_1.0+git53+8520b7c-r0_cortexa15hf-neon-vfpv4.ipk.
Configuring enigma2-plugin-systemplugins-satscanlcn.

Thanks

**Comment by Huevos** [comment]
Please provide a log of enigma2 start-up.

**Comment by estimadarocha** [comment]
The logging is enable by default? Location?

One more question yours NOS provider is it cable or sat?

**Comment by Huevos** [comment]
The plugin is for satellite only.
