### ISSUE TITLE
add simplitv

### ISSUE THREAD

**Issue by superlupo12** [Huevos/SatScanLcn#3]
hello,
austrian provider simplitv claims it also maintains an LCN table. here the params:

> 
> The simpliTV tuning option uses Nordig logical channel numbering descriptor which
> is broadcasted in the BAT of following Transponders on Astra 19.2°E:
> Parameter: Astra 1KR, 11273.25, H, 22000, 2/3
> 
> ```
> Bouquet_ID: 0x3700
> Bouquet_name: ORS comm GmbH & Co KG
> Country_Code_of_Validity: 905
> Private_data_specifier_ID: 0x000001B0
> ```

https://www.ors.at/fileadmin/user_upload/ors/downloads/sat-zertifizierung/simpliTV_Technical_Requirements_for_Tuning_Profile_implementation_for_Satellite_TVs_V11_final.pdf

if it's working, could you please add it to providers.py? thanks

i think the resulting list should be like this one: https://www.simplitv.at/media/documents/simpliTV-Senderliste_SAT_Plus.pdf

**Comment by Huevos** [comment]
Like this?

https://github.com/Huevos/SatScanLcn/commit/ae6fb2a7c1b95ad3b3a689dc8614d395c513d3b7

**Comment by superlupo12** [comment]
Thank you. Have you tried it yourself? For me, somethings seems to be wrong. It scans 101 transponders, but fails after 99 with message "Timeout for tuner lock on 12728". Another provider, "Austriasat", is working though (only scans 64 transponders)

**Comment by superlupo12** [comment]
Seems I cannot receive this transponder, which seems to be the highest active on Astra 19.2. Is there an option to skip broken transponders?

**Comment by Huevos** [comment]
Yes I ran it last night and it completed so all the transponders exist.

For the "skip" try this...
https://github.com/Huevos/SatScanLcn/commit/35c658df8961bace629e5cf5ca4e66c626a83f82

**Comment by superlupo12** [comment]
Yes, it's working now! Thank you very much!
