### ISSUE TITLE
Antiksat

### ISSUE THREAD

**Issue by Masterpicons** [Huevos/SatScanLcn#5]
I try to add  another provider to plugin. Scan are full over 200+ channels but again folder Antiksat are empty, and all channels are in last scan bouquet. How ever i found a fully paramets of this provider . Can You check it and tell me what I doing wrong? 
http://www.ab-forum.info/download/file.php?id=93127&mode=view  new
http://www.ab-forum.info/download/file.php?id=81116&mode=view  old
sorry for my eng.., 

   "Antiksat_0160": {
		"name": _("Antiksat"),
		"transponder": {
			"frequency": 11055000,
			"symbol_rate": 27500000,
			"polarization": eDVBFrontendParametersSatellite.Polarisation_Vertical,
			"fec_inner": eDVBFrontendParametersSatellite.FEC_4_5,
			"orbital_position": 160,
			"system": eDVBFrontendParametersSatellite.System_DVB_S2,
			"modulation": eDVBFrontendParametersSatellite.Modulation_QPSK,
			"roll_off": eDVBFrontendParametersSatellite.RollOff_auto,
			"original_network_id": 366,
			"transport_stream_id": 30400,
		},
	},

**Comment by Masterpicons** [comment]
https://www.satellite-calculations.com/DVB/get_psisi.php?16EAST_11055V/-1
i try study Your work at this page

**Comment by Huevos** [comment]
Empty because you were not fetching the LCNs.

According to you image from Transedit there is a BAT with BouquetID 0x1 so your provider needs to include that.

https://github.com/Huevos/SatScanLcn/commit/ca8dfc0efa7287fd9e3bdcaa474210b11bc29bc1

**Comment by Masterpicons** [comment]
Thanx. Now it`s works ok. Can You see to Cyfrowy Polsat provider. There are the same problem of empty bouquet after scan. Thanx for this issuse.

**Comment by Huevos** [comment]
For Polsat I see this...

![3](https://user-images.githubusercontent.com/2067864/212690599-4f8070b8-5a7b-4451-a3a9-349f8754a575.jpg)

**Comment by Masterpicons** [comment]
on my 2 E2 box i have empty bouquet..i will chewck on other systems. Many thanx fot Your work.

**Comment by Huevos** [comment]
No idea why. What image are you using?

**Comment by Masterpicons** [comment]
Egami py3 ver 10.1 i will try openpli and openatv

**Comment by Huevos** [comment]
All my plugins are built and tested on OpenViX.

**Comment by Masterpicons** [comment]
can You upload a latest version ipk?

**Comment by Huevos** [comment]
ipk is compiled so would need to be same python version.

**Comment by Masterpicons** [comment]
On openvix, after download from feed I must to replace  files:  plugin.pyc providers.pyc and satscanlcn.pyc to plugin.py, providers.py and satscanlcn.py downloaded from github with last changes. On VIX this works. Now I must try at Egami and write here.

**Comment by Masterpicons** [comment]
[SatScanLCN.tar.gz](https://github.com/Huevos/SatScanLcn/files/10449295/SatScanLCN.tar.gz)
ok, now it`s work. I don`t like ipk`s so I pack it to tar.gz

**Comment by Masterpicons** [comment]
![1_0_1_290E_1EDC_71_820000_0_0_0_20230118185145](https://user-images.githubusercontent.com/35345303/213259511-fa72a2a5-8a57-4f46-a34e-973276187408.jpg)
![1_0_1_290E_1EDC_71_820000_0_0_0_20230118185325](https://user-images.githubusercontent.com/35345303/213259515-7b9f8d99-9399-4cc3-97e5-2eb8a73fd4c1.jpg)
 I change the names of providers Cyfrowy Polsat to Polsat Box, and NC+ to Platforma Canal+
Thank You Huevos!

**Comment by Huevos** [comment]
Are these the official names?

**Comment by Masterpicons** [comment]
Yes.

**Comment by Masterpicons** [comment]
Polsat Box 
Platforma Canal+

**Comment by Huevos** [comment]
Like this:
https://github.com/Huevos/SatScanLcn/commit/1d80d84a19863552196df852e8049ccebadd3d19

**Comment by Masterpicons** [comment]
Yes
